// Las aventuras en orden. Cada una tiene una o varias fases (plataformas por defecto,
// o minijuegos: tiro, laberinto, tartas, mando, velas, patadita, maquillaje, examen, atrapar). Cada mapa tiene 12 filas.
// Leyenda: '.' aire  '#' suelo  'B' bloque  '=' plataforma (se atraviesa desde abajo)
//          '?' bloque regalo  'o' beso  'c' corazón  'R' recuerdo  'C' bandera de Alex
//          'G' meta  'S' salida  'w' bicho que anda  'f' bicho que vuela  'h' bicho que salta
//          'T' trampolín  '-' plataforma que se mueve de lado  '|' plataforma que sube y baja
//          '~' agua/lava/hueco (te devuelve a la última bandera)

const A = (texto) => ({ quien: 'Alex', texto });

// Une trozos de 12 filas (escritos uno debajo de otro) en un único mapa.
function mapa(...trozos) {
  const filas = Array(12).fill('');
  for (const t of trozos) {
    const lineas = t.trim().split('\n').map((l) => l.trim());
    if (lineas.length !== 12) console.warn('Trozo con', lineas.length, 'filas');
    const w = Math.max(...lineas.map((l) => l.length));
    lineas.forEach((l, i) => (filas[i] += l.padEnd(w, '.')));
  }
  return filas;
}

const FIN_SUELO = `
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
####################
####################`;

export const AVENTURAS = [
  // ------------------------------------------------------------------ 1
  {
    id: 'piscina',
    nombre: 'La piscina municipal',
    puerta: 'piscina',
    tema: 'piscina',
    enemigos: { w: 'patoGoma', f: 'mosquito', h: 'pelota' },
    jefe: 'flamenco',
    medalla: 'Medalla Chapuzón',
    objetivo: 'Ir a la Piscina Municipal',
    donde: 'Está en el centro del pueblo, al lado del bar. ¡La de la valla blanca!',
    intro: [A('¡Qué calor hace hoy! ¿Nos vamos a la piscina municipal?'), A('Cuidado con los mosquitos... y con los patos de goma, que vienen a por ti.')],
    pistas: [
      'Salta encima de los bichos para quitártelos de en medio.',
      'Si te caes al agua no pasa nada: vuelves a donde estaba yo.',
      'El trampolín te lanza muy alto. ¡Pruébalo!',
      'Los flotadores se mueven: espera a que estén cerca y salta.',
    ],
    recuerdo: { titulo: 'Tardes de piscina', texto: 'Las tardes de verano en la piscina de Valdemoro: toalla, crema y risas.' },
    despues: [A('¡Medalla Chapuzón! ¿Repetimos el verano que viene?')],
    mapa: mapa(
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ..........ooo.......
      ....................
      .........=====......
      ..S....o.o..........
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .......?............
      ....................
      ....................
      ...w.......o.o.o....
      ##########~~~#######
      ##########~~~#######`,
      `
      ....................
      ....................
      .............ooo....
      ....................
      ....................
      ....................
      ....................
      ..............BB....
      ............BBBB....
      .C.....T...BBBBBB...
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .......o..R..o......
      ....................
      .....---.....---....
      ....................
      ###~~~~~~##~~~~~~###
      ###~~~~~~##~~~~~~###`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      .........ooo........
      ........=====.......
      ....................
      ...=====.......f....
      .C.........h........
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ..........o.........
      .........o.o........
      ..w.....o...o...G...
      ####################
      ####################`,
      FIN_SUELO,
    ),
  },

  // ------------------------------------------------------------------ 2
  {
    id: 'lasertag',
    nombre: 'El láser tag',
    puerta: 'lasertag',
    tema: 'lasertag',
    jefe: 'jaimeRuben',
    medalla: 'Medalla Láser',
    objetivo: 'Ir al Láser Tag',
    donde: 'Está arriba a la izquierda, el edificio morado con luces de neón.',
    intro: [A('¡Hoy toca láser tag con Jaime, Rubén, Bea y más gente!'), A('Asoman por detrás de las cajas: apunta y dispara. ¡Pero a Bea no, que va contigo!')],
    pistas: [
      'Mueve la mira con la cruceta y dispara con A. ¡O toca directamente a quien quieras!',
      'La del chaleco azul es Bea: va en tu equipo.',
      'Los de delante son más grandes y más fáciles de acertar.',
    ],
    fases: [{ tipo: 'tiro' }],
    recuerdo: { titulo: 'Equipo imbatible', texto: 'Aquella partida de láser tag con los amigos: chalecos, luces de neón y muchos piques.' },
    despues: [A('¡Les has dado una paliza! Jaime y Rubén piden la revancha.')],
  },

  // ------------------------------------------------------------------ 3
  {
    id: 'thyssen',
    nombre: 'Arte en el Thyssen',
    puerta: 'estacion',
    tema: 'museo',
    medalla: 'Medalla Arte',
    objetivo: 'Coger el tren a Madrid (al Thyssen)',
    donde: 'La estación está abajo a la derecha, junto a las vías.',
    intro: [A('Hoy te llevo a Madrid: ¡al Museo Thyssen!')],
    fases: [
      {
        tipo: 'laberinto',
        intro: [
          A('Hoy te llevo a Madrid: ¡al Museo Thyssen!'),
          A('Vamos a coger las postales de los cuadros... pero el vigilante nos tiene fichados por ir corriendo.'),
          A('Coge las 5 postales y escapa por la puerta verde. ¡Que no te pille!'),
        ],
        pistas: [
          'El vigilante es más lento que tú: si te sigue, da la vuelta por otro pasillo.',
          'Las postales brillan. Hay una en cada rincón del museo.',
          'La salida es la puerta verde de abajo a la derecha.',
        ],
        recuerdo: false,
      },
      {
        tipo: 'tartas',
        intro: [
          A('¡Escapamos! Y ahora... ¡a Luna and Wanda!'),
          A('Hoy no las compramos: las hacemos nosotros. Yo te ayudo. Bueno, yo miro.'),
        ],
        pistas: [
          'Pulsa A muy rápido o toca la pantalla muchas veces para machacar las galletas.',
          'Mira la receta de la izquierda: el orden importa.',
          'Para batir, alterna izquierda y derecha. O toca un lado y luego el otro.',
          'En el horno, espera a que la aguja llegue a la zona verde.',
        ],
      },
    ],
    recuerdo: { titulo: 'Arte y tarta de queso', texto: 'Paseando entre cuadros en el Thyssen... y después, tarta de queso de Luna and Wanda.' },
    despues: [A('La nuestra está buena... pero las de Luna and Wanda siguen siendo las mejores.'), 'Alex compra tartas para llevar. ¡Recibes 3 TARTAS DE QUESO!'],
    premio: { tarta: 3 },
  },

  // ------------------------------------------------------------------ 4
  {
    id: 'series',
    nombre: 'Noche de series',
    puerta: 'casaSandra',
    tema: 'salon',
    jefe: 'tele',
    medalla: 'Medalla Sofá',
    objetivo: 'Ir a casa de Sandra (noche de series)',
    donde: 'Tu casa está a la izquierda, la del tejado rojo. ¡Laila nos espera en la puerta!',
    intro: [
      A('Hoy plan tranquilo: sofá, mantita y series en tu casa.'),
      A('Pero... ¿y el mando? Laila lo ha vuelto a esconder debajo de un cojín.'),
      A('Mira bien dónde lo mete y no le quites ojo a ese cojín cuando se mezclen.'),
    ],
    pistas: [
      'Sigue con los ojos solo el cojín del mando. Los demás dan igual.',
      'Cuando paren, elige con la cruceta y pulsa A. O toca el cojín directamente.',
      'Si fallas no pasa nada: Laila lo vuelve a esconder, y un poco más despacio.',
    ],
    fases: [{ tipo: 'mando' }],
    recuerdo: { titulo: 'Solo un capítulo más', texto: 'Las noches en tu casa viendo series sin hacer nada más... y sin necesitar nada más.' },
    despues: [A('Al final nos dormimos a mitad de capítulo, como siempre.'), 'Encuentras palomitas en el sofá. ¡Recibes 2 PALOMITAS!'],
    premio: { palomitas: 2 },
  },

  // ------------------------------------------------------------------ 5
  {
    id: 'cumple',
    nombre: 'El cumple de mi madre',
    puerta: 'casaAlex',
    tema: 'fiesta',
    jefe: 'tarta',
    medalla: 'Medalla Familia',
    objetivo: 'Ir a casa de Alex (cumple de su madre)',
    donde: 'Mi casa está a la derecha, la del tejado azul.',
    intro: [
      A('Hoy es el cumple de mi madre y vienes con toda mi familia.'),
      A('Tranquila, que les vas a encantar. Bueno... ya les encantas.'),
      A('Mira: las velas de la tarta se encienden en un orden. Repítelo igual y cantamos el cumpleaños feliz.'),
    ],
    pistas: [
      'Fíjate en el orden en que se encienden las velas y repítelo.',
      'Toca las velas, o elige con la cruceta y pulsa A.',
      'Si te equivocas, las vuelvo a encender. Sin prisa.',
    ],
    fases: [{ tipo: 'velas' }],
    recuerdo: { titulo: 'Una más de la familia', texto: 'El cumple de mi madre: tú, mi familia, la tarta... y tú ganándote a todos.' },
    despues: [A('Mi madre dice que vuelvas cuando quieras. Y lo dice en serio.')],
  },

  // ------------------------------------------------------------------ 6
  {
    id: 'comida',
    nombre: 'Comida con Begoña y David',
    puerta: 'casaSandra',
    tema: 'comedor',
    jefe: 'nervios',
    medalla: 'Medalla Aprobado',
    objetivo: 'Ir a casa de Sandra (comida con Begoña y David)',
    donde: 'Otra vez a tu casa, la del tejado rojo. Hoy toca comer con tu madre y con David.',
    intro: [
      A('Hoy como con tu madre y con David. Estoy... tranquilísimo.'),
      A('(No estoy nada tranquilo.)'),
      A('Si ves que voy a soltar alguna tontería, dame una patadita por debajo de la mesa. ¡Pero solo si hace falta!'),
    ],
    pistas: [
      'Pulsa A o toca la pantalla para darme la patadita.',
      'Lee lo que voy diciendo: si es algo bonito, déjame terminar.',
      'Si me voy a meter en un lío... ¡patadita antes de que acabe la frase!',
    ],
    fases: [{ tipo: 'patadita' }],
    recuerdo: { titulo: 'Examen superado', texto: 'El día que comí con Begoña y David. Nervios al principio y risas al final.' },
    despues: [A('¡Creo que les caí bien! David hasta se rió con mis chistes. Con uno.')],
  },

  // ------------------------------------------------------------------ 7
  {
    id: 'maquillaje',
    nombre: 'Noche de maquillaje',
    puerta: 'casaSandra',
    tema: 'salon',
    medalla: 'Medalla Glamour',
    objetivo: 'Ir a casa de Sandra (noche de maquillaje)',
    donde: 'A tu casa, la del tejado rojo. Esta noche el modelo soy yo...',
    intro: [
      A('Hoy toca noche de maquillaje... y el modelo soy yo.'),
      A('Me pongo la diadema de orejitas, me quito las gafas y... ¡hazme lo que quieras, bebe!'),
      A('Pinta con el dedo encima de mi cara. Abajo a la derecha tienes las pinturas.'),
    ],
    pistas: [],
    fases: [{ tipo: 'maquillaje' }],
    recuerdo: {
      titulo: 'Noche de maquillaje',
      texto: 'La noche que nos maquillamos: diadema de orejitas, colorete, pecas pintadas, besos de pintalabios... y foto con morritos.',
    },
    despues: [A('Mañana me desmaquillo. O no. Ya veremos.')],
  },

  // ------------------------------------------------------------------ 8
  {
    id: 'uni',
    nombre: 'Un día en tu uni',
    puerta: 'estacion',
    tema: 'uni',
    medalla: 'Medalla Matrícula',
    objetivo: 'Coger el tren a la uni',
    donde: 'Otra vez a la estación, abajo a la derecha. ¡Hoy me cuelo en tus clases!',
    intro: [
      A('Hoy me cuelo en tu uni a ver tus clases.'),
      A('¡Sorpresa! Hay examen... y el examen va de nosotros. Más te vale saberte las respuestas.'),
    ],
    pistas: [],
    fases: [{ tipo: 'examen' }],
    recuerdo: { titulo: 'Compañero de clase', texto: 'El día que fui a tu uni a ver tus clases. Me sentí muy orgulloso de ti.' },
    despues: [A('Qué lista eres. Yo no me enteré de nada, pero te miraba con cara de saberlo.')],
  },

  // ------------------------------------------------------------------ 9
  {
    id: 'cenas',
    nombre: 'Cenas de chef Alex',
    puerta: 'casaAlex',
    tema: 'cocina',
    jefe: 'aguacate',
    medalla: 'Medalla Chef',
    objetivo: 'Ir a casa de Alex (¡cena!)',
    donde: 'A mi casa, la del tejado azul. Hoy cocino yo.',
    intro: [
      A('¡Esta noche cocino yo! Menú: tartar de salmón con aguacate, baos y perrito asiático.'),
      A('Yo te voy lanzando los ingredientes y tú los coges con el bol. ¿Trato?'),
    ],
    pistas: [
      'Muévete con la cruceta o arrastrando el dedo por la pantalla.',
      'Lo negro está quemado. Y el calcetín... no sé qué hace ahí.',
      'Ya casi está la cena. ¡Un poco más!',
    ],
    fases: [{ tipo: 'atrapar' }],
    recuerdo: { titulo: 'Cocinando para ti', texto: 'Las veces que te hice la cena: tartar de salmón con aguacate, baos y el perrito asiático.' },
    despues: [A('Y al final la cena quedó buenísima, ¿a que sí?'), 'Sobran baos. ¡Recibes 2 BAOS DE ALEX!'],
    premio: { bao: 2 },
  },

  // ------------------------------------------------------------------ 10
  {
    id: 'rural',
    nombre: 'Casa rural en Cuevas del Valle',
    puerta: 'coche',
    tema: 'montana',
    enemigos: { w: 'cabra', f: 'avispa', h: 'pina' },
    jefe: 'cabraMontes',
    medalla: 'Medalla Gredos',
    amigos: ['bea', 'jaime', 'ruben'],
    objetivo: 'Coger el coche a Cuevas del Valle',
    donde: 'El coche está aparcado al lado de la estación, abajo a la derecha. ¡Todos al coche!',
    intro: [
      A('¡Escapada rural! Nos vamos todos juntos a una casa rural en Cuevas del Valle, en Ávila.'),
      A('Bea, Jaime y Rubén ya van subiendo al mirador. ¡Vamos a alcanzarlos!'),
    ],
    pistas: [
      'Las cabras de Gredos van a su aire. ¡Salta por encima!',
      'Ojo con las avispas, que en el monte hay un montón.',
      'Cruza la charca saltando de piedra en piedra.',
      'Arriba del todo está el mirador. ¡Foto de grupo!',
    ],
    recuerdo: { titulo: 'Foto en el mirador', texto: 'La escapada a la casa rural de Cuevas del Valle: la sierra, el mirador, la foto de grupo... y todos juntos.' },
    despues: [A('¡Qué vistas! Esta foto de grupo va directa al álbum.'), A('Y por la noche, cena todos juntos en la casa rural.')],
    mapa: mapa(
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .........o.o.o......
      ........BBBBB.......
      ....................
      ..S...........w.....
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ...............ooo..
      ....................
      ...........#########
      .......#############
      ...#################
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .........ooo........
      ...f................
      #####===========####
      #####...........####
      #####~~~~~~~~~~~####
      #####~~~~~~~~~~~####`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .........R..........
      ........BBB.........
      ####................
      ####.C.......w......
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      .....o...o...o......
      ....................
      ....................
      .....BB..BB..BB.....
      .C..................
      ####~~~~~~~~~~~~####
      ####~~~~~~~~~~~~####`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ...o.o.o............
      ....................
      ....................
      ..h.......w.....G...
      ####################
      ####################`,
      FIN_SUELO,
    ),
  },

  // ------------------------------------------------------------------ 11
  {
    id: 'madrid',
    nombre: 'Atardecer en Madrid',
    puerta: 'estacion',
    tema: 'madrid',
    enemigos: { w: 'patinete', f: 'paloma', h: 'churro' },
    jefe: 'alex',
    medalla: 'Medalla Atardecer',
    objetivo: 'Coger el tren a Madrid centro',
    donde: 'A la estación, abajo a la derecha. Última aventura... ¡la más bonita!',
    intro: [A('Última aventura: Madrid centro.'), A('Paseamos, nos perdemos un poco... y acabamos en el Templo de Debod. ¡Vamos!')],
    pistas: [
      'Las palomas de Madrid no tienen miedo a nada.',
      'Los patinetes van rapidísimo. ¡Salta por encima!',
      'Los churros saltan. Yo también saltaría si me fuesen a mojar en chocolate.',
      'Ya se ve el Templo de Debod. ¡Corre, que se nos pasa el atardecer!',
    ],
    recuerdo: { titulo: 'Atardecer en Debod', texto: 'Madrid centro, el atardecer en el Templo de Debod y después pizza en el Vesubio.' },
    despues: [],
    mapa: mapa(
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .........o.o.o......
      ........?.....?.....
      ....................
      ..S...........w.....
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ..........ooo.......
      ....................
      ....f...............
      ....................
      ....................
      ########...#########
      ########...#########`,
      `
      ....................
      ....................
      ....................
      ....................
      .........R..........
      ........===.........
      ....................
      .....===....===.....
      ....................
      .C..........w.......
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      .........ooo........
      ....................
      ....................
      ..---..===..---.....
      ....................
      #~~~~~~~~~~~~~~~~###
      #~~~~~~~~~~~~~~~~###`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .....ooo............
      ....BBBBB...........
      ....................
      .C.........h...w....
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ...o.o.o............
      ....................
      ....................
      ..w.....h.......G...
      ####################
      ####################`,
      FIN_SUELO,
    ),
  },
];

export function aventura(id) {
  return AVENTURAS.find((a) => a.id === id);
}
