// Las 10 aventuras (niveles) en orden. Cada mapa tiene 12 filas.
// Leyenda: '.' aire  '#' suelo  'B' bloque  '=' plataforma (se atraviesa desde abajo)
//          '?' bloque regalo  'o' beso  'c' corazón  'R' recuerdo  'C' bandera de Alex
//          'G' meta  'S' salida  'w' bicho que anda  'f' bicho que vuela  'h' bicho que salta
//          'T' trampolín  '-' plataforma que se mueve de lado  '|' plataforma que sube y baja
//          '~' agua/lava/hueco (te devuelve a la última bandera)

const A = (texto) => ({ quien: 'Alex', texto });

// Une trozos de 12 filas (escritos uno debajo de otro) en un único mapa.
function mapa(...trozos) {
  const filas = Array(12).fill('');
  for (const t of trozos) {
    const lineas = t.trim().split('\n').map((l) => l.trim());
    if (lineas.length !== 12) console.warn('Trozo con', lineas.length, 'filas');
    const w = Math.max(...lineas.map((l) => l.length));
    lineas.forEach((l, i) => (filas[i] += l.padEnd(w, '.')));
  }
  return filas;
}

const FIN_SUELO = `
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
####################
####################`;

export const AVENTURAS = [
  // ------------------------------------------------------------------ 1
  {
    id: 'piscina',
    nombre: 'La piscina municipal',
    puerta: 'piscina',
    tema: 'piscina',
    enemigos: { w: 'patoGoma', f: 'mosquito', h: 'pelota' },
    jefe: 'flamenco',
    medalla: 'Medalla Chapuzón',
    objetivo: 'Ir a la Piscina Municipal',
    donde: 'Está en el centro del pueblo, al lado del bar. ¡La de la valla blanca!',
    intro: [A('¡Qué calor hace hoy! ¿Nos vamos a la piscina municipal?'), A('Cuidado con los mosquitos... y con los patos de goma, que vienen a por ti.')],
    pistas: [
      'Salta encima de los bichos para quitártelos de en medio.',
      'Si te caes al agua no pasa nada: vuelves a donde estaba yo.',
      'El trampolín te lanza muy alto. ¡Pruébalo!',
      'Los flotadores se mueven: espera a que estén cerca y salta.',
    ],
    recuerdo: { titulo: 'Tardes de piscina', texto: 'Las tardes de verano en la piscina de Valdemoro: toalla, crema y risas.' },
    despues: [A('¡Medalla Chapuzón! ¿Repetimos el verano que viene?')],
    mapa: mapa(
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ..........ooo.......
      ....................
      .........=====......
      ..S....o.o..........
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .......?............
      ....................
      ....................
      ...w.......o.o.o....
      ##########~~~#######
      ##########~~~#######`,
      `
      ....................
      ....................
      .............ooo....
      ....................
      ....................
      ....................
      ....................
      ..............BB....
      ............BBBB....
      .C.....T...BBBBBB...
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .......o..R..o......
      ....................
      .....---.....---....
      ....................
      ###~~~~~~##~~~~~~###
      ###~~~~~~##~~~~~~###`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      .........ooo........
      ........=====.......
      ....................
      ...=====.......f....
      .C.........h........
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ..........o.........
      .........o.o........
      ..w.....o...o...G...
      ####################
      ####################`,
      FIN_SUELO,
    ),
  },

  // ------------------------------------------------------------------ 2
  {
    id: 'lasertag',
    nombre: 'El láser tag',
    puerta: 'lasertag',
    tema: 'lasertag',
    enemigos: { w: 'rival', f: 'dron', h: 'mina' },
    jefe: 'jaimeRuben',
    medalla: 'Medalla Láser',
    objetivo: 'Ir al Láser Tag',
    donde: 'Está arriba a la izquierda, el edificio morado con luces de neón.',
    intro: [A('¡Hoy toca láser tag con Jaime, Rubén, Bea y más gente!'), A('Jaime y Rubén van muy subiditos... ¡A por ellos!')],
    pistas: [
      'Los drones suben y bajan: pasa cuando estén arriba.',
      'Si caes por un hueco, vuelves a la última bandera. ¡Sin miedo!',
      'Bea dice que Jaime y Rubén se esconden al final del todo.',
      'La plataforma que sube y baja te lleva a un sitio secreto...',
    ],
    recuerdo: { titulo: 'Equipo imbatible', texto: 'Aquella partida de láser tag con los amigos: chalecos, luces de neón y muchos piques.' },
    despues: [A('¡Les has dado una paliza! Jaime y Rubén piden la revancha.')],
    mapa: mapa(
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      .........o.o.o......
      ....................
      ........BB?BB.......
      ....................
      ..S...........w.....
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ............ooo.....
      ...........=====....
      ........f...........
      ....=====...........
      ....................
      ###.......##########
      ###.......##########`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .......o......o.....
      ......BBB....BBB....
      ....................
      .C.......h..........
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ...........R........
      ..........BBB.......
      ....................
      .....|||............
      ....................
      ...o.......w....o...
      ###.......##########
      ###.......##########`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      .......ooo..........
      ......=====.........
      ....................
      ..=====.....f.......
      .C..........BB......
      ######......########
      ######......########`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .........ooo........
      ....................
      ....BB..............
      ..w.BB..h.......G...
      ####################
      ####################`,
      FIN_SUELO,
    ),
  },

  // ------------------------------------------------------------------ 3
  {
    id: 'thyssen',
    nombre: 'Arte en el Thyssen',
    puerta: 'estacion',
    tema: 'museo',
    enemigos: { w: 'turista', f: 'cuadro', h: 'busto' },
    jefe: 'marco',
    medalla: 'Medalla Arte',
    objetivo: 'Coger el tren a Madrid (al Thyssen)',
    donde: 'La estación está abajo a la derecha, junto a las vías.',
    intro: [A('Hoy te llevo a Madrid: ¡al Museo Thyssen!'), A('Y después... tartas de queso de Luna and Wanda. Pero primero, un poco de arte.')],
    pistas: [
      'Los cuadros vuelan. Esto no pasa en los museos normales.',
      'Ojo con los turistas del flash, van a lo suyo.',
      'Por arriba, saltando de repisa en repisa, hay algo escondido.',
      'Al final de la sala te espera un cuadro con muy mal humor.',
    ],
    recuerdo: { titulo: 'Arte y tarta de queso', texto: 'Paseando entre cuadros en el Thyssen... y después, tarta de queso de Luna and Wanda.' },
    despues: [A('¡Ahora sí: a por esas tartas de queso de Luna and Wanda!'), 'Alex compra tartas para llevar. ¡Recibes 3 TARTAS DE QUESO!'],
    premio: { tarta: 3 },
    mapa: mapa(
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ..........o.o.o.....
      .........=======....
      ....................
      ..S..........w......
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....ooo.............
      ...=====............
      ....................
      ..........f.........
      ...............h....
      ###########...######
      ###########...######`,
      `
      ....................
      ....................
      ....................
      ....................
      .............o......
      ............BBB.....
      ....................
      .......BBB..........
      ....................
      .C..BBB.........w...
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      .........R..........
      ........===.........
      ....................
      .....===....===.....
      ....................
      ..===..........===..
      ....................
      ###...##########....
      ###...##########....`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      .......ooooo........
      ....................
      ....................
      ...f.........f......
      .C..................
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ...o.o.o............
      ....................
      ...........BB.......
      ..h...w....BB...G...
      ####################
      ####################`,
      FIN_SUELO,
    ),
  },

  // ------------------------------------------------------------------ 4
  {
    id: 'series',
    nombre: 'Noche de series',
    puerta: 'casaSandra',
    tema: 'salon',
    enemigos: { w: 'mando', f: 'spoiler', h: 'palomitas' },
    jefe: 'tele',
    medalla: 'Medalla Sofá',
    objetivo: 'Ir a casa de Sandra (noche de series)',
    donde: 'Tu casa está a la izquierda, la del tejado rojo. ¡Laila nos espera en la puerta!',
    intro: [A('Hoy plan tranquilo: sofá, mantita y series en tu casa.'), A('Pero cuidado... ¡hay SPOILERS sueltos por el salón! Y el suelo es lava.')],
    pistas: [
      'Los fantasmas son spoilers. ¡Que no te toquen!',
      'El suelo es lava. Bueno, de mentira. Pero no lo pises.',
      'Los cojines del sofá aguantan, súbete encima.',
      'Ya casi estamos... solo un capítulo más. (Mentira.)',
    ],
    recuerdo: { titulo: 'Solo un capítulo más', texto: 'Las noches en tu casa viendo series sin hacer nada más... y sin necesitar nada más.' },
    despues: [A('Al final nos dormimos a mitad de capítulo, como siempre.'), 'Encuentras palomitas en el sofá. ¡Recibes 2 PALOMITAS!'],
    premio: { palomitas: 2 },
    mapa: mapa(
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .........o.o.o......
      ........BBBBBBB.....
      ....................
      ..S.........h.......
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ...........ooo......
      ..........=====.....
      ....................
      .....====......f....
      ....................
      ####~~~~~~~~~~~#####
      ####~~~~~~~~~~~#####`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      .........R..........
      ........BBB.........
      ....................
      ....BBB......BBB....
      .C..BBB..f...BBB....
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .......o..o..o......
      ....................
      ....---......---....
      ....................
      ###~~~~~~##~~~~~~###
      ###~~~~~~##~~~~~~###`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ..........ooo.......
      .........=====......
      ....................
      ....=====...........
      .C..........w...h...
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .....o.o.o..........
      ....BBBBBBB.........
      ....................
      ..w......h......G...
      ####################
      ####################`,
      FIN_SUELO,
    ),
  },

  // ------------------------------------------------------------------ 5
  {
    id: 'cumple',
    nombre: 'El cumple de mi madre',
    puerta: 'casaAlex',
    tema: 'fiesta',
    enemigos: { w: 'gorrito', f: 'globo', h: 'regalo' },
    jefe: 'tarta',
    medalla: 'Medalla Familia',
    objetivo: 'Ir a casa de Alex (cumple de su madre)',
    donde: 'Mi casa está a la derecha, la del tejado azul.',
    intro: [A('Hoy es el cumple de mi madre y vienes con toda mi familia.'), A('Tranquila, que les vas a encantar. Bueno... ya les encantas.')],
    pistas: [
      'Los globos flotan arriba y abajo, ¡písalos!',
      'Los regalos saltan solos. Esta familia es rarita.',
      'Cuidado con la piscina de bolas, que no tiene fondo.',
      'Al final está la tarta. Una tarta... con muy malas pulgas.',
    ],
    recuerdo: { titulo: 'Una más de la familia', texto: 'El cumple de mi madre: tú, mi familia, la tarta... y tú ganándote a todos.' },
    despues: [A('Mi madre dice que vuelvas cuando quieras. Y lo dice en serio.')],
    mapa: mapa(
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      .........ooo........
      ....................
      ........?B?B?.......
      ....................
      ..S...........w.....
      ####################
      ####################`,
      `
      ....................
      ....................
      ...........ooo......
      ....................
      ..........=====.....
      ....................
      ....................
      ....................
      ..f.................
      .......T........h...
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ..........R.........
      .........BBB........
      ....................
      .....BBB.......f....
      .C...BBB............
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ....o...o...o.......
      ....................
      ...===..===..===....
      ....................
      ##~~~~~~~~~~~~~~~###
      ##~~~~~~~~~~~~~~~###`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      .........ooo........
      ....................
      ....................
      ......----..........
      .C..................
      #####~~~~~~~~#######
      #####~~~~~~~~#######`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ...o.o.o.o..........
      ....................
      .........BB.........
      ..w..h...BB.....G...
      ####################
      ####################`,
      FIN_SUELO,
    ),
  },

  // ------------------------------------------------------------------ 6
  {
    id: 'comida',
    nombre: 'Comida con Begoña y David',
    puerta: 'casaSandra',
    tema: 'comedor',
    enemigos: { w: 'croqueta', f: 'pregunta', h: 'olla' },
    jefe: 'nervios',
    medalla: 'Medalla Aprobado',
    objetivo: 'Ir a casa de Sandra (comida con Begoña y David)',
    donde: 'Otra vez a tu casa, la del tejado rojo. Hoy toca comer con tu madre y con David.',
    intro: [A('Hoy como con tu madre y con David. Estoy... tranquilísimo.'), A('(No estoy nada tranquilo.)')],
    pistas: [
      'Las preguntas incómodas vuelan por todas partes. ¡Esquívalas!',
      'Las croquetas de Begoña están buenísimas, pero estas muerden.',
      'El suelo es sopa. No preguntes.',
      'Al final te espera... mi propio nerviosismo. Calma, que tú sabes.',
    ],
    recuerdo: { titulo: 'Examen superado', texto: 'El día que comí con Begoña y David. Nervios al principio y risas al final.' },
    despues: [A('¡Creo que les caí bien! David hasta se rió con mis chistes. Con uno.')],
    mapa: mapa(
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ..........ooo.......
      .........=====......
      ....................
      ....=====...........
      ..S..........w......
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .............ooo....
      ...f................
      .......===..=====...
      ....................
      ######.....#########
      ######.....#########`,
      `
      ....................
      ....................
      ....................
      ....................
      ..........R.........
      .........===........
      ....................
      .....===.....===....
      ....................
      .C..........h.......
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ...........ooo......
      ..........BBBBB.....
      ....................
      ...f................
      .C.....w.......w....
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ....o.o.....o.o.....
      ....................
      ...----.....----....
      ....................
      ##~~~~~~~##~~~~~~~##
      ##~~~~~~~##~~~~~~~##`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ....ooo.............
      ...=====............
      ....................
      .........h...h..G...
      ####################
      ####################`,
      FIN_SUELO,
    ),
  },

  // ------------------------------------------------------------------ 7
  {
    id: 'uni',
    nombre: 'Un día en tu uni',
    puerta: 'estacion',
    tema: 'uni',
    enemigos: { w: 'libro', f: 'apunte', h: 'cafe' },
    jefe: 'examen',
    medalla: 'Medalla Matrícula',
    objetivo: 'Coger el tren a la uni',
    donde: 'Otra vez a la estación, abajo a la derecha. ¡Hoy me cuelo en tus clases!',
    intro: [A('Hoy me cuelo en tu uni a ver tus clases.'), A('Prometo no dormirme. (No prometo nada.)')],
    pistas: [
      'Los apuntes vuelan. Típico.',
      'El café salta de los nervios. Normal, es café.',
      'Sube por los pupitres para encontrar algo especial.',
      'Al final hay un examen. Pero tú eres la lista de los dos.',
    ],
    recuerdo: { titulo: 'Compañero de clase', texto: 'El día que fui a tu uni a ver tus clases. Me sentí muy orgulloso de ti.' },
    despues: [A('Qué lista eres. Yo no me enteré de nada, pero te miraba con cara de saberlo.')],
    mapa: mapa(
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .........?.?.?......
      ....................
      ....................
      ..S.........w.......
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      .............ooo....
      ............=====...
      ....................
      ........=====.......
      ....................
      ....=====.......f...
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .........ooo........
      ........BBBBB.......
      ....................
      .C..............h...
      ###...##############
      ###...##############`,
      `
      ....................
      ....................
      ....................
      ...........R........
      ..........===.......
      ....................
      ......===...........
      ....................
      ..===...............
      ............f.......
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      .........ooo........
      ....................
      ....................
      .....---....---.....
      .C..................
      ####~~~~~##~~~~#####
      ####~~~~~##~~~~#####`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ....o.o.o...........
      ...BBBBBBB..........
      ....................
      ...w......w.....G...
      ####################
      ####################`,
      FIN_SUELO,
    ),
  },

  // ------------------------------------------------------------------ 8
  {
    id: 'cenas',
    nombre: 'Cenas de chef Alex',
    puerta: 'casaAlex',
    tema: 'cocina',
    enemigos: { w: 'aguacate', f: 'gota', h: 'bao' },
    jefe: 'aguacate',
    medalla: 'Medalla Chef',
    objetivo: 'Ir a casa de Alex (¡cena!)',
    donde: 'A mi casa, la del tejado azul. Hoy cocino yo.',
    intro: [
      A('¡Esta noche cocino yo! Menú: tartar de salmón con aguacate, baos y perrito asiático.'),
      A('El problema es que la comida... ¡se ha rebelado!'),
    ],
    pistas: [
      'Las gotas de aceite saltan de la sartén. ¡Queman!',
      'Los baos botan. Están muy esponjosos.',
      'El trampolín es una tabla de cortar. No preguntes cómo.',
      'Al final te espera el aguacate más duro del mundo.',
    ],
    recuerdo: { titulo: 'Cocinando para ti', texto: 'Las veces que te hice la cena: tartar de salmón con aguacate, baos y el perrito asiático.' },
    despues: [A('Y al final la cena quedó buenísima, ¿a que sí?'), 'Sobran baos. ¡Recibes 2 BAOS DE ALEX!'],
    premio: { bao: 2 },
    mapa: mapa(
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ..........ooo.......
      .........BBBBB......
      ....................
      ....................
      ..S.....h.......w...
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ..........ooo.......
      .........=====......
      ....===.............
      ...f................
      #####~~~~~~~~~~#####
      #####~~~~~~~~~~#####`,
      `
      ....................
      ....................
      ....................
      ....................
      .........R..........
      ........BBB.........
      ....................
      ....BBB.............
      ....BBB.............
      .C..BBB.......w.....
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ........ooo.........
      ....................
      ....................
      ....................
      ....................
      ....................
      .C.h...T.....h......
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .....o.....o........
      ....................
      ...----...----......
      ....................
      ##~~~~~~~~~~~~~~####
      ##~~~~~~~~~~~~~~####`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ...o.o.o.o..........
      ....................
      ..........BB........
      ....w.....BB....G...
      ####################
      ####################`,
      FIN_SUELO,
    ),
  },

  // ------------------------------------------------------------------ 9
  {
    id: 'rural',
    nombre: 'Casa rural en Cuevas del Valle',
    puerta: 'coche',
    tema: 'montana',
    enemigos: { w: 'cabra', f: 'avispa', h: 'pina' },
    jefe: 'cabraMontes',
    medalla: 'Medalla Gredos',
    amigos: ['bea', 'jaime', 'ruben'],
    objetivo: 'Coger el coche a Cuevas del Valle',
    donde: 'El coche está aparcado al lado de la estación, abajo a la derecha. ¡Todos al coche!',
    intro: [
      A('¡Escapada rural! Nos vamos todos juntos a una casa rural en Cuevas del Valle, en Ávila.'),
      A('Bea, Jaime y Rubén ya van subiendo al mirador. ¡Vamos a alcanzarlos!'),
    ],
    pistas: [
      'Las cabras de Gredos van a su aire. ¡Salta por encima!',
      'Ojo con las avispas, que en el monte hay un montón.',
      'Cruza la charca saltando de piedra en piedra.',
      'Arriba del todo está el mirador. ¡Foto de grupo!',
    ],
    recuerdo: { titulo: 'Foto en el mirador', texto: 'La escapada a la casa rural de Cuevas del Valle: la sierra, el mirador, la foto de grupo... y todos juntos.' },
    despues: [A('¡Qué vistas! Esta foto de grupo va directa al álbum.'), A('Y por la noche, cena todos juntos en la casa rural.')],
    mapa: mapa(
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .........o.o.o......
      ........BBBBB.......
      ....................
      ..S...........w.....
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ...............ooo..
      ....................
      ...........#########
      .......#############
      ...#################
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .........ooo........
      ...f................
      #####===========####
      #####...........####
      #####~~~~~~~~~~~####
      #####~~~~~~~~~~~####`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .........R..........
      ........BBB.........
      ####................
      ####.C.......w......
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      .....o...o...o......
      ....................
      ....................
      .....BB..BB..BB.....
      .C..................
      ####~~~~~~~~~~~~####
      ####~~~~~~~~~~~~####`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ...o.o.o............
      ....................
      ....................
      ..h.......w.....G...
      ####################
      ####################`,
      FIN_SUELO,
    ),
  },

  // ------------------------------------------------------------------ 10
  {
    id: 'madrid',
    nombre: 'Atardecer en Madrid',
    puerta: 'estacion',
    tema: 'madrid',
    enemigos: { w: 'patinete', f: 'paloma', h: 'churro' },
    jefe: 'alex',
    medalla: 'Medalla Atardecer',
    objetivo: 'Coger el tren a Madrid centro',
    donde: 'A la estación, abajo a la derecha. Última aventura... ¡la más bonita!',
    intro: [A('Última aventura: Madrid centro.'), A('Paseamos, nos perdemos un poco... y acabamos en el Templo de Debod. ¡Vamos!')],
    pistas: [
      'Las palomas de Madrid no tienen miedo a nada.',
      'Los patinetes van rapidísimo. ¡Salta por encima!',
      'Los churros saltan. Yo también saltaría si me fuesen a mojar en chocolate.',
      'Ya se ve el Templo de Debod. ¡Corre, que se nos pasa el atardecer!',
    ],
    recuerdo: { titulo: 'Atardecer en Debod', texto: 'Madrid centro, el atardecer en el Templo de Debod y después pizza en el Vesubio.' },
    despues: [],
    mapa: mapa(
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .........o.o.o......
      ........?.....?.....
      ....................
      ..S...........w.....
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ..........ooo.......
      ....................
      ....f...............
      ....................
      ....................
      ########...#########
      ########...#########`,
      `
      ....................
      ....................
      ....................
      ....................
      .........R..........
      ........===.........
      ....................
      .....===....===.....
      ....................
      .C..........w.......
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      .........ooo........
      ....................
      ....................
      ..---..===..---.....
      ....................
      #~~~~~~~~~~~~~~~~###
      #~~~~~~~~~~~~~~~~###`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      .....ooo............
      ....BBBBB...........
      ....................
      .C.........h...w....
      ####################
      ####################`,
      `
      ....................
      ....................
      ....................
      ....................
      ....................
      ....................
      ...o.o.o............
      ....................
      ....................
      ..w.....h.......G...
      ####################
      ####################`,
      FIN_SUELO,
    ),
  },
];

export function aventura(id) {
  return AVENTURAS.find((a) => a.id === id);
}
